custom:
  - https://affiliate.notion.so/inlqolf5id34
  - https://airtable.com/invite/r/8eOiv4I4
  - https://m.do.co/c/b2a387de5da4
  - https://m.do.co/c/00f73acd0fc8
  - https://www.linode.com/lp/refer/?r=2380225d05c74b69bd7e553a8c763808733fc71f
